fix(evm): update claims on claim
boostxyz/boost-protocol pull request #263
Opened 2024-11-06 22:20 UTC by Quazia

🚨 Please review the [guidelines for contributing](https://github.com/boostxyz/boost-protocol/blob/main/.github/CONTRIBUTING.md) to this repository.

### Description
Added claim increment on the variable incentives
💔 Thank you!

2024-11-06 22:21 UTC, sammccord commented
<!--
  1 failure:  Your PR body must...
  1 warning:  Are you sure you ...
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Your PR body must reference a Github issue using a valid keyword, or your PR title must include the internal Boost ticket number, ie: `[BOOST-1234] Innovate like nuts`
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Are you sure you want to be submitting a change without including a changeset? If you're just changing docs or tests, you probably don't need to. See [the publishing section of the README](https://github.com/boostxyz/boost-protocol?tab=readme-ov-file#changesets--publishing) for more info.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e171472cf1f168248403d250db84aab712710cee
</p>

2024-11-06 22:21 UTC, sammccord commented
<!--
  1 failure:  Your PR body must...
  1 warning:  Are you sure you ...
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Your PR body must reference a Github issue using a valid keyword, or your PR title must include the internal Boost ticket number, ie: `[BOOST-1234] Innovate like nuts`
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Are you sure you want to be submitting a change without including a changeset? If you're just changing docs or tests, you probably don't need to. See [the publishing section of the README](https://github.com/boostxyz/boost-protocol?tab=readme-ov-file#changesets--publishing) for more info.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e171472cf1f168248403d250db84aab712710cee
</p>

2024-11-06 22:21 UTC, topocount approved these changes

2024-11-06 22:26 UTC, sammccord approved these changes

2024-11-06 22:33 UTC, jonathandiep commented on packages/evm/contracts/incentives/ERC20VariableIncentive.sol
> +        claims += 1;
I think this `claims += 1` is in the wrong place?

Should happen on `claim()`, not `initialize()`

2024-11-06 22:33 UTC, jonathandiep requested changes

2024-11-06 22:33 UTC, jonathandiep commented on packages/evm/contracts/incentives/ERC20VariableIncentive.sol
> +        claims += 1;
I think this claims += 1 is in the wrong place?

Should happen on claim(), not initialize()

2024-11-07 01:09 UTC, sammccord commented
<!--
  0 failure: 
  2 warning:  By using the `[AD..., Are you sure you ...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  By using the `[ADHOC]` title prefix, you are bypassing best practice protections.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Are you sure you want to be submitting a change without including a changeset? If you're just changing docs or tests, you probably don't need to. See [the publishing section of the README](https://github.com/boostxyz/boost-protocol?tab=readme-ov-file#changesets--publishing) for more info.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cd08927ce5841c8ea2f8c4881c9c3119155d3f39
</p>

2024-11-07 01:10 UTC, jonathandiep approved these changes

2024-11-07 15:30 UTC, merged