Jon/deploy pegged incentive
boostxyz/boost-protocol pull request #308
Opened 2024-12-04 21:39 UTC by jonathandiep

🚨 Please review the [guidelines for contributing](https://github.com/boostxyz/boost-protocol/blob/main/.github/CONTRIBUTING.md) to this repository.

### Description
Please describe your pull request

💔 Thank you!

2024-12-04 21:40 UTC, sammccord commented
<!--
  1 failure:  Your PR body must...
  1 warning:  Are you sure you ...
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Your PR body must reference a Github issue using a valid keyword, or your PR title must include the internal Boost ticket number, ie: `[BOOST-1234] Innovate like nuts`
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Are you sure you want to be submitting a change without including a changeset? If you're just changing docs or tests, you probably don't need to. See [the publishing section of the README](https://github.com/boostxyz/boost-protocol?tab=readme-ov-file#changesets--publishing) for more info.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 033270db1a02e3645b6272a3f99ef3daa76efde7
</p>

2024-12-04 23:30 UTC, sammccord commented
<!--
  1 failure:  Your PR body must...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Your PR body must reference a Github issue using a valid keyword, or your PR title must include the internal Boost ticket number, ie: `[BOOST-1234] Innovate like nuts`
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8dd39d5d09f7f0855624dfcb9dc7cff9bfc604d2
</p>

2024-12-05 17:52 UTC, Quazia requested changes

2024-12-05 17:52 UTC, Quazia commented on packages/sdk/src/Incentives/ERC20PeggedIncentive.ts
> +  public async peg(params?: ReadParams) {
[I think this covers the need already](https://github.com/boostxyz/boost-protocol/blob/57f089f706a0dc52b3e26de3177068c3a05b20f1/packages/sdk/src/Incentives/ERC20PeggedIncentive.ts#L366)

2024-12-05 19:57 UTC, sammccord commented
<!--
  0 failure: 
  1 warning:  By using the `[AD...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  By using the `[ADHOC]` title prefix, you are bypassing best practice protections.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 25dac1859d07d32483a21d7ddb24180c20916396
</p>

2024-12-05 20:00 UTC, sammccord commented
<!--
  0 failure: 
  1 warning:  By using the `[AD...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  By using the `[ADHOC]` title prefix, you are bypassing best practice protections.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cebecf874ca448f74463fbdba35b4ab79b7ef1cc
</p>

2024-12-05 20:02 UTC, Quazia approved these changes
LG - thanks for the comment cleanup 😅

2024-12-05 20:09 UTC, merged